// Code generated by cmd/cgo; DO NOT EDIT.

package main

import "unsafe"

import "syscall"

import _cgopackage "runtime/cgo"

type _ _cgopackage.Incomplete
var _ syscall.Errno
func _Cgo_ptr(ptr unsafe.Pointer) unsafe.Pointer { return ptr }

//go:linkname _Cgo_always_false runtime.cgoAlwaysFalse
var _Cgo_always_false bool
//go:linkname _Cgo_use runtime.cgoUse
func _Cgo_use(interface{})
type _Ctype_PDF = _Ctype_struct_PDF_s

type _Ctype_struct_PDF_s _cgopackage.Incomplete

type _Ctype_void [0]byte

//go:linkname _cgo_runtime_cgocall runtime.cgocall
func _cgo_runtime_cgocall(unsafe.Pointer, uintptr) int32

//go:linkname _cgoCheckPointer runtime.cgoCheckPointer
func _cgoCheckPointer(interface{}, interface{})

//go:linkname _cgoCheckResult runtime.cgoCheckResult
func _cgoCheckResult(interface{})

//go:cgo_import_static _cgo_ef0f50123b0e_Cfunc_PDF_new
//go:linkname __cgofn__cgo_ef0f50123b0e_Cfunc_PDF_new _cgo_ef0f50123b0e_Cfunc_PDF_new
var __cgofn__cgo_ef0f50123b0e_Cfunc_PDF_new byte
var _cgo_ef0f50123b0e_Cfunc_PDF_new = unsafe.Pointer(&__cgofn__cgo_ef0f50123b0e_Cfunc_PDF_new)

//go:cgo_unsafe_args
func _Cfunc_PDF_new() (r1 *_Ctype_struct_PDF_s) {
	_cgo_runtime_cgocall(_cgo_ef0f50123b0e_Cfunc_PDF_new, uintptr(unsafe.Pointer(&r1)))
	if _Cgo_always_false {
	}
	return
}
