// Code generated by cmd/cgo; DO NOT EDIT.

//line /home/athul/pdflib/pdflib10/cmd/main.go:1:1
package main




// #cgo LDFLAGS: -L /home/athul/pdflib/pdflib10/lib/ -lpdf-linux
// #include "pdflib.h"
// #include "golang.h"
import _ "unsafe"


func main() {
	_ = ( /*line :13:6*/_Cfunc_PDF_new /*line :13:14*/)();

}